#
# NOTICE: This file is synchronized on-demand by synchronize.yaml job from a shared library directory
#
# CUSTOMIZATION: Please edit .github/helpers/ci-vars.env to modify values that are injected
#

name: Test
on:
    pull_request:
    push:

env:
    KEEP_CLUSTER: yes  # speed up by not deleting the Kubernetes cluster at beginning of tests. As the cluster is created in a Github Action before

jobs:
    test:
        uses: riotkit-org/pipelines/pipelines/python-release-on-tag/.github/workflows/test.yaml@main
