#
# NOTICE: This file is synchronized on-demand by synchronize.yaml job from a shared library directory
#
# CUSTOMIZATION: Please edit .github/helpers/ci-vars.env to modify values that are injected
#

name: Test
on:
    pull_request:
    push:

env:
    KEEP_CLUSTER: yes  # speed up by not deleting the Kubernetes cluster at beginning of tests. As the cluster is created in a Github Action before
    PYTHON_VERSION: 3.10

jobs:
    test:
        uses: riotkit-org/pipelines/.github/workflows/propagate.yaml@9b2d50ae84eba903add61edb006e4f5265a41b05
